pull_request_rules:
  - name: automatic merge on CI success; delete branch afterwards
    conditions:
      - status-success=buddy/pipeline/test
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: {}
