pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=continuous-integration/buddy/test
    actions:
      merge:
        method: merge
        strict: true
