language: generic
sudo: false
cache:
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin"
matrix:
    include:
        - os: linux
        - os: osx
before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TAR_OPTS=""; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TAR_OPTS="--wildcards"; fi
- if [ ! -f $HOME/.local/bin/stack ]; then travis_retry curl -L https://www.stackage.org/stack/$TRAVIS_OS_NAME-x86_64
  | tar -xzO $TAR_OPTS '*/stack' > ~/.local/bin/stack; fi
- chmod a+x ~/.local/bin/stack
install:
- stack setup --no-terminal
- stack build --only-snapshot --no-terminal
script:
- stack build --no-terminal --test
before_deploy:
  - git config --local user.name "scoiatael"
  - git config --local user.email "czapl.luk+git@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(ruby -ryaml -e "puts YAML.load_file('package.yaml').fetch('version')")}
  - git tag $TRAVIS_TAG
  - cp $(stack exec -- which geeknote-converter) geeknote-converter-$TRAVIS_OS_NAME
  - export RELEASE_TITLE=$(date '+%Y%m%d%H%M%S')-$(echo "$TRAVIS_COMMIT_MESSAGE" | tail -n 1)
deploy:
  name: $RELEASE_TITLE
  skip_cleanup: true
  draft: true
  provider: releases
  api_key:
    secure: WJhOroaCpFTfw8dAhe3A9ZoA6hEmQSZQii8EBg93u/1PUJnaErhY4S/E5dS/Sr/Hlpns9m086hvtUEO337Dg6BPvFXJ8xpPOeFfebvzzwctwKqkHFHRZj50eIcxWSbAkPk7fzEdSbbkURfPLZtqE2UFLM2XvQ5YlOFx3Vh8sS5QXrR+yBNedAuDYLCoM+NkUUfiegcT/mohakvZACl9yQpN5z05IpwA4qnlmOSougpEFmrcQTRhp9TPyoR6QR61+0cKCfzUvkL0JuKLE38p0QIC3ILaUyxvUMfldBsUe9fjhlvAuAo6QBa2WnqqKzTJ8CRz57z6DCM56EnqaSM9hRnSINiItTkXIVEV50d9fLcJnpzeULdScYhA/5MANcdnvntn1WzfFP005OHvoO5H5b7XSPKc+sk6bLEvhm1rjiEYq7utA6oGXgMn20iVZkAQs6LwMaQEvndRCPja7ANZy6vYSJfcL2REUaClPFQaB6PKaCuUXL1JoD+jvawNrOEEOLmQLNd4yVAPEII8/g6GauTWKuRuVRT/ObonuYeytKCe/tATKcRORMKvePyTztOii2JmWVxOyOSAUOJhklpfxWauHjV45JfJsMMWxKJwXx3bXVUAfO81zLxatNUcBSXVuaz6p1bPKD8Xoy15K/i+S/puljVscVHswqIRLoxOf54k=
  file: geeknote-converter-$TRAVIS_OS_NAME
  on:
    repo: scoiatael/geeknote-converter
    branch: master
    os: osx
