name:                geeknote-converter
version:             0.1.0.0
github:              "scoiatael/geeknote-converter"
license:             BSD3
author:              "Lukasz Czaplinski"
maintainer:          "czapl.luk+git@gmail.com"
copyright:           "2019 Lukasz Czaplinski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/scoiatael/geeknote-converter#readme>

dependencies:
- base >= 4.7 && < 5
- cmark
- text
- bytestring
- transformers
- cli
- raw-strings-qq
- xml-conduit
- containers

library:
  source-dirs: src

executables:
  geeknote-converter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geeknote-converter

tests:
  geeknote-converter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geeknote-converter
    - hspec
    - QuickCheck
    - directory
